version: "3"

tasks:
  run-dev-api:
    cmds:
      - go run cmd/main.go cmd/plugins.go -confPath configs/cube-api.yaml
  dev-dev-mongo:
    cmds:
      - docker run -d -p 27017:27017 --name cube-mongo mongo:4.2
  check:
    cmds:
      - task: vet
      - task: diff-mod
      - task: diff-api-docs
  build:
    cmds:
      - task: binary
  vet:
    cmds:
      - go vet ./...
  diff-mod:
    cmds:
      - go mod tidy
      - git diff --exit-code go.mod go.sum
  diff-api-docs:
    cmds:
      - git diff --exit-code api
  test:
    cmds:
      - go test -v ./...
  binary:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o bin/cube-api cmd/main.go
  update-api-docs:
    cmds:
      - swag init --output ./api -g ./cmd/main.go ./cmd/plugins.go
