kind: http
metadata:
  name: cube-cos-api
  version: v1.0.0
spec:
  listen:
    port: 8001
    address:
      local: 0.0.0.0
      advertise: 0.0.0.0
  store:
    mongodb:
      uri: mongodb://0.0.0.0:27017
      database: cube-cos
      replicaSet: cube-cos-rs
      auth:
        enabled: true
        username: admin
        password: admin
    influxdb:
      url: http://0.0.0.0:8086
  dependency:
    cubeCos: /etc/settings.txt
    openstack:
      confFile: /etc/admin-openrc.sh
      auth:
        type: "password"
        url: "http://10.32.10.180:5000/v3"
        username: "admin"
        password: "admin"
        project:
          name: "admin"
          domain:
            name: "default"
    k3s: /etc/rancher/k3s/k3s.yaml
  log:
    file: /var/log/cube-cos-api/access.log
    level: 2
    rotation:
      backups: 3
      size: 20
      ttl: 30
      compress: true
